version: "3.7"

services:
  hydra:
    build: 
      context: .
      dockerfile: ./hydra.Dockerfile
    container_name: hydra
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - auth-db
      - hydra-migrate
    networks:
      - intranet

  auth-db:
    image: mysql:8.0.26
    container_name: auth-db
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - intranet

  hydra-migrate:
    build: 
      context: .
      dockerfile: ./hydra-migrate.Dockerfile
    container_name: hydra-migrate
    env_file:
      - ./.env
    depends_on:
      - auth-db
    restart: on-failure
    networks:
      - intranet

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v2.2.0-rc.3
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet
networks:
  intranet:
